_sql_database_table = "useful when you want to know the table in SQL.\\n"
_sql_database_select = "useful when you want to know the target selected in SQL.\\n"

_sql_QA_data_format = "use following format : \\n"
_sql_orign_Question = "the input question you must answer.\\n"
_sql_orign_Thought = "you should always think about what to do.\\n"
_sql_orign_Action = "the input to the action.\\n"
_sql_orign_Obervation = "the result of the action.\\n"
_sql_orign_seperator = "....(this Thought/Action/Action input/Observation can repeat N times)\\n"
_sql_orign_final = "the final answer to the original input question.\\n"
_sql_orign_begin = "begin!\\n"
