import communication

prompt = ("use following format:"
          "Role: never forgot role you have played."
          "task: task you must done."
          "think: choose one or more tools from [table,field,join]."
          "input: information generated by tool , is you got nothing , set it to NULL."
          "output: output final answer and say goodbye.")

history = ("now we have following tool:"
           "table : useful when you want to find database tables correctly."
           "field : useful when you want to find fields correctly."
           "join : useful when you want to know the relationship between tables.")

response = communication.post(role="Assistant", post_input=prompt, history=history)
answer_text = response["data"]
choices = answer_text["choices"][0]
content = choices["content"]
history = choices["history"]
print(history)
print("#####################", end="\n")

# prompt_by_user =
