import communication
import random

prompt = ("now we have following tools:\n"
          "table : useful when you want to find database tables correctly.\n"
          "field : useful when you want to find fields correctly.\n"
          "join : useful when you want to know the relationship between tables.\n"

          "Answer me use following format:\n"
          "Role: never forgot role you have played.\n"
          "task: task you must done.\n"
          "think: choose one or more tools from [table,field,join].\n"
          "input: information generated by tool , is you got nothing , set it to NULL.\n"
          "output: output final answer and say goodbye.\n")


def print_result(llm_response):
    answer_text = llm_response["data"]
    choices = answer_text["choices"][0]
    # use request_id to force in one conversion
    request_id = answer_text["request_id"]

    content = choices["content"]
    contexts = content.split("\\n")
    for i in range(len(contexts)):
        text = contexts[i]
        if len(text) > 0:
            print(f"contexts = {text}", end="\n")


random_int = random.randint(1000, 100000)
print(f"request_id={random_int}")

response = communication.post(role="Assistant", post_input=prompt, request_id=str(random_int))
print_result(response)

task = ("task:generate SQL , query the 8th's payment of alex. "
        "input:after using table tool, I hava found following tables in the database."
        "1、user_user_customer: include name,address,code information of customer."
        "2、customer_profile: include consumption information of customer."
        "3、order_main: include order,discount information of customer."
        "input:after using join tool,I have determined relationship between tables."
        "1、user_user_customer and customer_profile: one to many , key is customer_code."
        "2、customer_profile and order_main：one to one , key is customer_code."
        "3、user_user_customer and order_main: one to many, key is customer_code "
        "input:after using field tool,I have found following fields in the tables"
        "user_user_customer："
        "   1、customer_name: name of customer."
        "   2、customer_code: id of customer."
        "   3、create_time: reg time of customer"
        "customer_profile:"
        "   1、profile_id: id of profile"
        "   2、month_consumption：month consumption."
        "   3、year_consumption：year consumption."
        "   4、date_consumption：date of consumption."
        "order_main: "
        "   1、profile_id: consumption id for each order"
        "   2、customer_code: id of customer."
        "   3、order_id: id of order"
        "   4、order_status: vale must one of [on,off]")

print(task)
new_response = communication.post(role="User", post_input=task, request_id=str(random_int))
print_result(new_response)


# prompt_by_user =
